### ISSUE TITLE
It also looks like that basic-file must be on the top of project folder:

### ISSUE THREAD

**Issue by chunkypixel** [chunkypixel/batariBasic-extension#2]
It also looks like that basic-file must be on the top of project folder:

1. I opened folder "pothole" with "pothole.bas" file and build project - everything is fine (pothole/pothole.bas)

2. I opened folder "atari2600" with subfolder "games" with subfolder "pothole" and tried to build pothole.bas (atari2600/games/pothole/pothole.bas):
```
Starting build of pothole.bas
/Users/vbauer/.vscode/extensions/chunkypixel.bataribasic-0.1.6/out/bin/BB.1.1d.reveng41/2600basic.sh: line 36: pothole.bas: No such file or directory
```

_Originally posted by @vbauer in https://github.com/chunkypixel/batariBasic-extension/issues/1#issuecomment-482812649_

**Comment by chunkypixel** [comment]
Build v.0.1.7
Fixed issue compiling a file which was located in a subfolder of the open workspace (thanks vbauer!)

**Comment by vbauer** [comment]
It was very quick! Everything works great, thank you
